from __future__ import annotations

from typing import Any


class ApiCollector:
    """
    Captures the API responses generated by LOAM.

    APIs we care about:

    1. chapter-stats
    2. roster
    3. student-chapter-stats
    4. question-stats
    """

    CHAPTER_STATS_PATH = "/api/answer-crops/chapter-stats"
    ROSTER_PATH = "/api/answer-crops/roster"
    STUDENT_CHAPTER_STATS_PATH = (
        "/api/answer-crops/student-chapter-stats"
    )
    QUESTION_STATS_PATH = (
        "/api/answer-crops/question-stats"
    )

    def __init__(self) -> None:

        self.clear()

    # =========================================================
    # RESET
    # =========================================================

    def clear(self) -> None:
        """
        Clear all previously captured API responses.

        This is important when moving from one
        Grade-Section to another.
        """

        self.chapter_stats: Any | None = None
        self.roster: Any | None = None
        self.student_chapter_stats: Any | None = None
        self.question_stats: Any | None = None

        self.captured_urls: list[str] = []

    # =========================================================
    # PLAYWRIGHT RESPONSE HANDLER
    # =========================================================

    def handle_response(self, response) -> None:
        """
        Called automatically by Playwright whenever
        the browser receives an HTTP response.
        """

        url = response.url

        # Ignore APIs that are not relevant to validation.
        if not self._is_relevant_api(url):
            return

        # Only process successful responses.
        if response.status != 200:
            print(
                f"⚠ Relevant API returned "
                f"status {response.status}: {url}"
            )
            return

        try:
            data = response.json()

        except Exception as exc:

            print(
                f"⚠ Could not parse JSON from API:\n"
                f"  {url}\n"
                f"  Error: {exc}"
            )

            return

        self.captured_urls.append(url)

        # -----------------------------------------------------
        # Chapter stats
        # -----------------------------------------------------

        if self.CHAPTER_STATS_PATH in url:

            self.chapter_stats = data

            print("✓ chapter-stats API detected")
            print(f"  URL: {url}")
            print(f"  Status: {response.status}")

        # -----------------------------------------------------
        # Roster / student scores
        # -----------------------------------------------------

        elif self.ROSTER_PATH in url:

            self.roster = data

            print("✓ roster API detected")
            print(f"  URL: {url}")
            print(f"  Status: {response.status}")

        # -----------------------------------------------------
        # Student chapter stats
        # -----------------------------------------------------

        elif self.STUDENT_CHAPTER_STATS_PATH in url:

            self.student_chapter_stats = data

            print(
                "✓ student-chapter-stats API detected"
            )

            print(f"  URL: {url}")
            print(f"  Status: {response.status}")

        # -----------------------------------------------------
        # Question stats
        # -----------------------------------------------------

        elif self.QUESTION_STATS_PATH in url:

            self.question_stats = data

            print("✓ question-stats API detected")
            print(f"  URL: {url}")
            print(f"  Status: {response.status}")

    # =========================================================
    # API DETECTION
    # =========================================================

    def _is_relevant_api(self, url: str) -> bool:
        """
        Return True only if the URL belongs to one of
        the four APIs required by our validation.
        """

        return any(
            path in url
            for path in (
                self.CHAPTER_STATS_PATH,
                self.ROSTER_PATH,
                self.STUDENT_CHAPTER_STATS_PATH,
                self.QUESTION_STATS_PATH,
            )
        )

    # =========================================================
    # GETTERS
    # =========================================================

    def get_chapter_stats(self) -> Any:
        """
        Return chapter-wise section statistics.
        """

        if self.chapter_stats is None:

            raise RuntimeError(
                "chapter-stats API response was not captured."
            )

        return self.chapter_stats

    def get_roster(self) -> Any:
        """
        Return student roster / marks data.
        """

        if self.roster is None:

            raise RuntimeError(
                "roster API response was not captured."
            )

        return self.roster

    def get_student_chapter_stats(self) -> Any:
        """
        Return student chapter-wise statistics.
        """

        if self.student_chapter_stats is None:

            raise RuntimeError(
                "student-chapter-stats API response "
                "was not captured."
            )

        return self.student_chapter_stats

    def get_question_stats(self) -> Any:
        """
        Return question-wise statistics.
        """

        if self.question_stats is None:

            raise RuntimeError(
                "question-stats API response was not captured."
            )

        return self.question_stats

    # =========================================================
    # VALIDATION HELPERS
    # =========================================================

    def missing_apis(self) -> list[str]:
        """
        Return the names of APIs that have not been captured.
        """

        missing = []

        if self.chapter_stats is None:
            missing.append("chapter-stats")

        if self.roster is None:
            missing.append("roster")

        if self.student_chapter_stats is None:
            missing.append("student-chapter-stats")

        if self.question_stats is None:
            missing.append("question-stats")

        return missing

    def all_required_apis_captured(self) -> bool:
        """
        Return True only when all four required APIs
        have been captured.
        """

        return not self.missing_apis()